image: node:9.4.0

cache:
  paths:
    - node_modules/

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - build

Build:
  stage: build
  tags:
    - node
  before_script: 
    - npm install 
  script:
    - npm run build