image: node:19.9.0

cache:
  paths:
    - node_modules/

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - build

Build:
  stage: build
  tags:
    - gitlab-org
  before_script: 
    - npm install 
  script:
    - npm run build